services:
  server:
    container_name: server_barbershop
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - main
    restart: unless-stopped

  client:
    container_name: client_barbershop
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    driver: bridge
    external: true
